service:
  extensions: [jaeger_storage, jaeger_query]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [jaeger_storage_exporter]

extensions:
  jaeger_query:
    trace_storage: memstore
    trace_storage_archive: memstore_archive
    ui_config: ./cmd/jaeger/config-ui.json

  jaeger_storage:
    badger_primary:
      memstore:
        directory_key: "/tmp/jaeger/"
        directory_value: "/tmp/jaeger/"
        ephemeral: false
        maintenance_interval: 5
        metrics_update_interval: 10
      memstore_archive:
        directory_key: "/tmp/jaeger_archive/"
        directory_value: "/tmp/jaeger_archive/"
        ephemeral: false
        maintenance_interval: 5
        metrics_update_interval: 10

receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  jaeger_storage_exporter:
    trace_storage: memstore
